site_name:        GenieAuthentication.jl
repo_url:         https://github.com/GenieFramework/GenieAuthentication.jl
site_description: GenieAuthentication - Authentication plugin for Genie
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
